### ISSUE TITLE
multiple notifications for warnings

### ISSUE THREAD

**Issue by mr-gosh** [Reamer/icinga2-mattermost#10]
perhaps someone can clarify how to setup the number of notification re-posts.
It kind of a bit too much spam if the messages get repeatedly posted for the same issue.

I think this need to be setup in the icinga side - or is there an easier way to achive this?

**Comment by Reamer** [comment]
Checkout your Notification-Object - Config-Documentation for this object https://icinga.com/docs/icinga2/latest/doc/09-object-types/#notification
`interval` and `period` are the right configuration parameters for your problem. I can recommend the [netways training](https://www.netways.de/trainings/icinga-fundamentals/). I've met the people this year in chemnitz, they are really nice.

**Comment by Reamer** [comment]
No response after one month. Closing Issue.
