### ISSUE TITLE
notification problem from icinga exchange

### ISSUE THREAD

**Issue by Reamer** [Reamer/icinga2-mattermost#5]
Original Comments: https://exchange.icinga.com/Reamer/icinga2-mattermost/comments
History:

DavideM78 2019-01-06 12:20:54
> Hi! I followed your HOWTO step by step but I can't get any notification on my Mattermost channel. Could you please provide me some help? Tanks in advance, Davide

Reamer 2019-01-06 14:53:22
> Hi, have you checked out the project page on GitHub (https://github.com/Reamer/icinga2-mattermost)?

DavideM78 2019-01-07 16:04:20

> Hi, and thank you for your reply . Yes I checked this project out and followed your guide step by step, but I can't get any notification on my Mattermost channel. If you need some details or config files, please don't hesitate to ask me. Best, Davide

**Comment by Reamer** [comment]
@DavideM78 
Please let us check, that the plugin works as expected without icinga .
```bash
./mattermost.py --url https://chat.mycompany.de/hooks/xxxxxxxxxxxxxx --notificationtype Problem --hostalias "testhost" 
```
Output on shell should be a simply `ok` and in your chat platform you should see the message `Problem testhost is None - None` from icinga bot.

Is this working for you?

**Comment by DavideM78** [comment]
Hi @Reamer yes the plugin works locally on all the hosts that are involved.
Maybe it could be usefull to you  if  I explane which kind of setup I have:
It is a Distributed Monitoring with 1 Master + 2 Satellites + 2 Clients like that:

![icinga2_distributed_scenarios_master_satellite_client](https://user-images.githubusercontent.com/32898704/50956424-e9796e00-14bb-11e9-86d4-f4d9bcf3f9c7.png)
All the checks works good between Master/Satellites/Clients and on Icinga Dashboard I get the correct value, so the general setup is correct. It is just with this plugin that I have problems.
Thanks.

**Comment by Reamer** [comment]
Did you see some errors in debug log? On witch node Master or Satellites you want to trigger this plugin?

**Comment by DavideM78** [comment]
In Log I see that notification has been sanded (but actually not) and the plugin runs on the Master node and it should report all the Master/Satellite/Client's events.

**Comment by Reamer** [comment]
Good to know, that the mattermost notification plugin is triggered. Have you tested manual the plugin  on your master node (Maybe a firewall issue)?
In icinga debug log you should see the complete command which is executed. You could also execute the plugin from command line with all parameters. (maybe an encoding problem)

**Comment by DavideM78** [comment]
Hi Reamer, yes when I execute the plug in from the command line I have no problems to get the notification on my Mattermost channel. That's the problem, the plug in works only from the command line.

**Comment by DavideM78** [comment]
Here is the error the  I found in debug.log:
```
[2019-01-17 09:40:59 +0100] warning/PluginUtility: Error: Non-optional macro 'mattermonst_serviceoutput' used in argument '--serviceoutput' is missing.

[2019-01-17 09:40:59 +0100] warning/PluginNotificationTask: Notification command for object 'munin.inwx.net!http' (PID: -1, arguments: 'sh' '-c' '') terminated with exit code 3, output: Error: Non-optional macro 'mattermonst_serviceoutput' used in argument '--serviceoutput' is missing.
```

**Comment by DavideM78** [comment]
Ok, solved. The log was very clear. Just added the non optional macro, it was missing.
Thank you for your support and congratulation for your work.

**Comment by Reamer** [comment]
You are welcome.
