### ISSUE TITLE
don't use --username or --channel

### ISSUE THREAD

**Issue by TonyBostonTB** [Reamer/icinga2-mattermost#6]
Don't know if this was true before but with Mattermost Version: 5.6.2 you'll want to not use --channel or --username here as this would give you an HTTP 404
Tried a few times until I didn't use either variable and it did work. Could anyone confirm this?

**Comment by Reamer** [comment]
Hi @TonyBostonTB,
I use Mattermost in version 5.7.1. I use a custom `--channel` parameter and the default `--username` parameter (icinga).
On this [site](https://developers.mattermost.com/integrate/incoming-webhooks/) you can check out, that `channel` and `username` are supported in payload.

**Comment by Reamer** [comment]
Hi @TonyBostonTB,
can I help you with your issue? Maybe you solved your issue already, possible with a updated  Mattermost.
Best Regards
Reamer

**Comment by TonyBostonTB** [comment]
@Reamer no, I just wanted to see if anyone else has this. It is working for me without giving the channel or username.

**Comment by Ataraxxia** [comment]
This should be mentioned in the main readme, as it made me waste good 2 hours trying to figure out why I was getting 404's for no good reason. Dropping the --channel helped.
