### ISSUE TITLE
installation description not understandable from readme

### ISSUE THREAD

**Issue by mr-gosh** [Reamer/icinga2-mattermost#8]
where the commands should be setup is not really understandable from the redme file.

i try to follow the steps - but its absolutely not self explaing - perhaps I can fix this after i was able to get it to work, but possibly this won't happen. So if you have something more verbose laying around that could be helpfull.

For example you say "create notification command" - in the icinga2 documentation is written that long commands should be put into shell scripts - but possibly your snippet doesn't seem to be shell code anyway - so what to do? post all of that into the one liner through the director?

**Comment by Reamer** [comment]
Hi @mr-gosh,
If you have improvements for the readme, I'm open for Pull-Request.
I doesn't use the director feature of icinga2. Please place all needed files into the configuration directory of icinga2 (`/etc/icinga2/conf.d/`).
My "snippets" are valid configuration files.

**Comment by mr-gosh** [comment]
yeah - i recognized that meanwhile - but still i fail on restarting icinga2 when the notifications are in place.
when either "" or "" or both are copied to the notifications.conf the restart is refused with hte output of:
```
# systemctl restart icinga2
Job for icinga2.service failed because the control process exited with error code.
See "systemctl status icinga2.service" and "journalctl -xe" for details.
```

and with *systemctl status icinga2* the output is:

```
Mar 25 17:02:00 prd-mon01 icinga2[9705]: /etc/icinga2/conf.d/notifications.conf(37):   command = "mattermost_host"
Mar 25 17:02:00 prd-mon01 icinga2[9705]:                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Reamer** [comment]
Have you copied both `NotificationCommand` objects to your configuration? It seems that the `Notification` can not find the `NotificationCommand` "mattermost_host".

**Comment by mr-gosh** [comment]
Yes - both are in there.
I checked twice if something is missing and I found a lonely "/*" command - after removing it i now get this output after the "systemctl reload icinga2" command:

```
# systemctl status icinga2.service
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: active (running) (Result: exit-code) since Mon 2019-03-25 20:39:15 CET; 12h ago
  Process: 7280 ExecReload=/usr/lib/icinga2/safe-reload /etc/default/icinga2 (code=exited, status=1/FAILURE)
  Process: 1483 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/default/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 1537 (icinga2)
    Tasks: 17
   CGroup: /system.slice/icinga2.service
           ├─1537 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           └─1656 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log

Mar 26 09:00:08 prd-mon01 safe-reload[7280]: [2019-03-26 09:00:08 +0100] critical/config: Error: Object 'mail-host-notification' of type 'NotificationCommand'
Mar 26 09:00:08 prd-mon01 safe-reload[7280]: Location: in /etc/icinga2/conf.d/commands.conf: 147:1-147:51
Mar 26 09:00:08 prd-mon01 safe-reload[7280]: /etc/icinga2/conf.d/commands.conf(145):
Mar 26 09:00:08 prd-mon01 safe-reload[7280]: /etc/icinga2/conf.d/commands.conf(146):
Mar 26 09:00:08 prd-mon01 safe-reload[7280]: /etc/icinga2/conf.d/commands.conf(147): object NotificationCommand "mail-host-notification" {
Mar 26 09:00:08 prd-mon01 safe-reload[7280]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 09:00:08 prd-mon01 safe-reload[7280]: /etc/icinga2/conf.d/commands.conf(148):   command = [ ConfigDir + "/scripts/mail-host-notification.sh" ]
Mar 26 09:00:08 prd-mon01 safe-reload[7280]: /etc/icinga2/conf.d/commands.conf(149):
Mar 26 09:00:08 prd-mon01 systemd[1]: icinga2.service: Control process exited, code=exited status=1
Mar 26 09:00:08 prd-mon01 systemd[1]: Reload failed for Icinga host/service/network monitoring system.

```

**Comment by mr-gosh** [comment]
did i get it right:
**2. Create the notification command** needs to be put in **commands.conf**
**3. Create the mattermost User** needs to be put in **users.conf**
and **4. Apply notifications to mattermost User** needs to be put in **notifications.conf**?

**Comment by Reamer** [comment]
It doesn't matter where you put the configuration. It's only important that icinga2 reads the configuration file.
You can also put all snippets in one configuration file under `/etc/icinga2/conf.d`

**Comment by mr-gosh** [comment]
ok - but what could produce above error?

**Comment by Reamer** [comment]
Can you upload your whole `commands.conf` in a [gist](https://gist.github.com/)?

**Comment by Reamer** [comment]
> ok - but what could produce above error?

The error message seems not complete.

**Comment by mr-gosh** [comment]
> Can you upload your whole `commands.conf` in a [gist](https://gist.github.com/)?

https://gist.github.com/mr-gosh/1bf93ebaa227db3a4a49704d5a671594

**Comment by mr-gosh** [comment]
> > ok - but what could produce above error?
> 
> The error message seems not complete.

This is the whole output
```
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: failed (Result: exit-code) since Tue 2019-03-26 14:27:21 CET; 47s ago
  Process: 2744 ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 2728 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/default/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 2744 (code=exited, status=1/FAILURE)

Mar 26 14:27:21 prd-mon01 icinga2[2744]: Location: in /etc/icinga2/conf.d/commands.conf: 147:1-147:51
Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(145):
Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(146):
Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(147): object NotificationCommand "mail-host-notification" 
Mar 26 14:27:21 prd-mon01 icinga2[2744]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(148):   command = [ ConfigDir + "/scripts/mail-host-notifi
Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(149):
Mar 26 14:27:21 prd-mon01 systemd[1]: icinga2.service: Main process exited, code=exited, status=1/FAILURE
Mar 26 14:27:21 prd-mon01 systemd[1]: icinga2.service: Failed with result 'exit-code'.
Mar 26 14:27:21 prd-mon01 systemd[1]: Failed to start Icinga host/service/network monitoring system.
```

**Comment by Reamer** [comment]
You have defined `NotificationCommand "mail-host-notification"` and `NotificationCommand "mail-service-notification"` twice.
 `NotificationCommand "mail-host-notification"`
1) https://gist.github.com/mr-gosh/1bf93ebaa227db3a4a49704d5a671594#file-commands-conf-L9
2) https://gist.github.com/mr-gosh/1bf93ebaa227db3a4a49704d5a671594#file-commands-conf-L147

`NotificationCommand "mail-service-notification"`
1) https://gist.github.com/mr-gosh/1bf93ebaa227db3a4a49704d5a671594#file-commands-conf-L68
2) https://gist.github.com/mr-gosh/1bf93ebaa227db3a4a49704d5a671594#file-commands-conf-L165

Please use only one as describe in this comment https://gist.github.com/mr-gosh/1bf93ebaa227db3a4a49704d5a671594#file-commands-conf-L138

**Comment by Reamer** [comment]
> fi

**Comment by Reamer** [comment]
> > > ok - but what could produce above error?
> > 
> > 
> > The error message seems not complete.
> 
> This is the whole output
> 
> ```
> ● icinga2.service - Icinga host/service/network monitoring system
>    Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
>   Drop-In: /etc/systemd/system/icinga2.service.d
>            └─limits.conf
>    Active: failed (Result: exit-code) since Tue 2019-03-26 14:27:21 CET; 47s ago
>   Process: 2744 ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
>   Process: 2728 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/default/icinga2 (code=exited, status=0/SUCCESS)
>  Main PID: 2744 (code=exited, status=1/FAILURE)
> 
> Mar 26 14:27:21 prd-mon01 icinga2[2744]: Location: in /etc/icinga2/conf.d/commands.conf: 147:1-147:51
> Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(145):
> Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(146):
> Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(147): object NotificationCommand "mail-host-notification" 
> Mar 26 14:27:21 prd-mon01 icinga2[2744]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(148):   command = [ ConfigDir + "/scripts/mail-host-notifi
> Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(149):
> Mar 26 14:27:21 prd-mon01 systemd[1]: icinga2.service: Main process exited, code=exited, status=1/FAILURE
> Mar 26 14:27:21 prd-mon01 systemd[1]: icinga2.service: Failed with result 'exit-code'.
> Mar 26 14:27:21 prd-mon01 systemd[1]: Failed to start Icinga host/service/network monitoring system.
> ```

systemd cuts the output on the right site as you can see in this line
`Mar 26 14:27:21 prd-mon01 icinga2[2744]: /etc/icinga2/conf.d/commands.conf(148):   command = [ ConfigDir + "/scripts/mail-host-notifi`[cation ...]

Please use `journalctl -u icinga2` and scroll to the end.

**Comment by Reamer** [comment]
Any other questions or can we close this issue?

**Comment by mr-gosh** [comment]
it seems to work now! many thanks - i try to integrate this into the documentation - so it should be easier to understand for first starters.... ;)
