### ISSUE TITLE
plugin location unclear

### ISSUE THREAD

**Issue by mr-gosh** [Reamer/icinga2-mattermost#9]
after being able to drop the test message to mattermost - the normally triggered messages fail to get pushed cause of wrong script location?

> terminated with exit code 128, output: execvpe(/usr/
lib/nagios/plugins/icinga2-mattermost/mattermost.py) failed: No such file or directory

after copying the script to the desired location too - it still fails with a different error message

```
warning/PluginNotificationTask: Notification command for object <sniped stuff away> terminated with exit code 1, output: Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/icinga2-mattermost/mattermost.py", line 100, in <module>
    response = request(args.url, data)
  File "/usr/lib/nagios/plugins/icinga2-mattermost/mattermost.py", line 94, in request
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by mr-gosh** [comment]
I am sure this is because of some wired config on my side - but perhaps someone has an idea what is wrong here... :/

**Comment by Reamer** [comment]
Scan access logs of your mattermost-server. Do you find request from your icinga2 server?

**Comment by Reamer** [comment]
You define the plugin location with object NotificationCommand "mattermost_service" and "mattermost_host".

**Comment by mr-gosh** [comment]
Triggering the script by hand via something like this works perfectly and i get an psot to the mattermsot channel...

> /usr/share/icingaweb2/modules/director/contrib/icinga2-mattermost/mattermost.py --url https://mattermostinstance.de/withentrypoint --notificationtype CUSTOM --hostalias icingatest.com

thats why i did not search for problems on the mattermsot server...

**Comment by mr-gosh** [comment]
to get rid of the path problem i now integrated the full path without the variable in the Command definitions

**Comment by Reamer** [comment]
Maybe you hit this problem. #6

**Comment by mr-gosh** [comment]
indeed i found a typo, i was using channel "icinga2" and not "icinga" - so both came together - it now works, by replacing the path variable with the exact location and by using the right channel name.

THX!
